# NeON build file (http://github.com/c4s4/neon)

extends:
- c4s4/build/golang.yml
- c4s4/build/release.yml

properties:
  NAME:    'changelog'
  LIBRARIES:
  - 'github.com/mitchellh/gox'
  - 'gopkg.in/yaml.v2'
