# NeON build file (http://github.com/c4s4/neon)

extends:
- c4s4/build/golang.yml

properties:
  LIBRARIES:
  - 'gopkg.in/yaml.v2'

targets:

  bin:
    steps:
    - mkdir: =BUILD_DIR
    - $: ['go', 'build', '-o', '={BUILD_DIR}/changelog']
