name:    changelog
doc:     Build changelog project
default: test
extends: :go:simple-command.yml

properties:
  NAME:      "changelog"
  DEPENDENCIES:
  - "gopkg.in/yaml.v2"
  - "github.com/mitchellh/gox"

targets:

  archive:
    doc: Build distribution archive
    steps:
    - mkdir: "#{BUILD_DIR}/#{NAME}-#{VERSION}/bin/"
    - mkdir: "#{BUILD_DIR}/#{NAME}-#{VERSION}/sh/" 
    - 'gox -output=#{ARC_DIR}/bin/{{.Dir}}_{{.OS}}_{{.Arch}}'
    - copy:
      - "LICENSE.txt"
      - "CHANGELOG.yml"
      todir: "#{ARC_DIR}"
    - 'md2pdf -o #{ARC_DIR}/README.pdf README.md'
    - copy:  "release"
      todir: "#{ARC_DIR}/sh/"
    - tar: "**/*"
      dir: "#{ARC_DIR}"
      prefix: "#{NAME}-#{VERSION}"
      to: "#{BUILD_DIR}/#{NAME}-#{VERSION}.tar.gz"
